Feature: eSIM Profile Download via APN3 for TESTING Plan Lines

  Scenario: Verify that lines on TESTING plan can download eSIM profile using APN3 in preproductive environment
    Given a GM line is provisioned on TESTING plan with APN3 configured as preproductive
    When the user initiates the eSIM profile download process from the device using APN3
    And the eSIM profile download completes successfully
    Then the device should be activated without errors
    And the traffic generated by APN3 during download should have zero cost in BSCS7
    And the invoice should not include charges for the eSIM profile download