Feature: Pre-billing Shell Execution Validation for General Motors

  Scenario: Verify In Pool calculation Shell executes correctly before pre-billing without interfering with other processes
    Given the BSCS7 system is available and shells are deployed
    And the TIM.BSCST_FECT_RNG_PARAM parameter table is configured
    When I identify the scheduled date and time for GM pre-billing process
    Then I should see the exact start date and time with cutoff on day 29 of the month
    When I manually execute the sh_BSCS_ProcesoFacturaGM shell before pre-billing schedule
    Then the shell should start correctly and register in the process control table with identifier GM-sequential
    When I verify in system logs that the shell does not run simultaneously with IZZIPAY shell
    Then I should see both shells execute at different times without conflicts in shared tables
    When I confirm the shell completes and generates OCCs in Document All table before pre-billing starts
    Then the In Pool Service and In Pool Granel Service OCCs should be registered and available for standard pre-billing
    When the standard pre-billing process starts after shell completion
    Then pre-billing should process the OCCs generated by the shell without errors or inconsistencies