const { Given, When, Then } = require('@cucumber/cucumber');
const { expect } = require('@playwright/test');
const ESIMDownloadPage = require('../pages/ESIMDownloadPage');

let esimDownloadPage;

Given('a GM line is provisioned on TESTING plan with APN3 configured as preproductive', async function () {
  esimDownloadPage = new ESIMDownloadPage(this.page);
  await esimDownloadPage.navigateToProvisioningPanel();
  await esimDownloadPage.selectTestingPlan();
  await esimDownloadPage.configureAPN3AsPreproductive();
  await esimDownloadPage.provisionGMLine();
  const isProvisioned = await esimDownloadPage.verifyLineProvisioned();
  expect(isProvisioned).toBeTruthy();
});

When('the user initiates the eSIM profile download process from the device using APN3', async function () {
  await esimDownloadPage.navigateToESIMDownloadSection();
  await esimDownloadPage.selectAPN3Connection();
  await esimDownloadPage.initiateESIMProfileDownload();
  const connectionEstablished = await esimDownloadPage.verifyAPN3ConnectionEstablished();
  expect(connectionEstablished).toBeTruthy();
});

When('the eSIM profile download completes successfully', async function () {
  await esimDownloadPage.waitForDownloadCompletion();
  const downloadSuccess = await esimDownloadPage.verifyDownloadSuccess();
  expect(downloadSuccess).toBeTruthy();
});

Then('the device should be activated without errors', async function () {
  const activationStatus = await esimDownloadPage.getDeviceActivationStatus();
  expect(activationStatus).toBe('activated');
  const hasErrors = await esimDownloadPage.checkForActivationErrors();
  expect(hasErrors).toBeFalsy();
});

Then('the traffic generated by APN3 during download should have zero cost in BSCS7', async function () {
  await esimDownloadPage.navigateToBSCS7Console();
  await esimDownloadPage.queryUDRTable();
  const trafficCost = await esimDownloadPage.getAPN3TrafficCost();
  expect(trafficCost).toBe('0.00');
});

Then('the invoice should not include charges for the eSIM profile download', async function () {
  await esimDownloadPage.navigateToInvoiceSection();
  await esimDownloadPage.searchCurrentInvoice();
  const apn3Charges = await esimDownloadPage.getAPN3ChargesFromInvoice();
  expect(apn3Charges).toBe('0.00');
  const hasESIMDownloadCharges = await esimDownloadPage.verifyNoESIMDownloadCharges();
  expect(hasESIMDownloadCharges).toBeFalsy();
});