const { Given, When, Then } = require('@cucumber/cucumber');
const { expect } = require('@playwright/test');
const PreBillingShellPage = require('../pages/PreBillingShellPage');

let preBillingShellPage;

Given('the BSCS7 system is available and shells are deployed', async function () {
  preBillingShellPage = new PreBillingShellPage(this.page);
  await preBillingShellPage.navigateToSystemMonitor();
  const isAvailable = await preBillingShellPage.verifyBSCS7SystemAvailability();
  expect(isAvailable).toBeTruthy();
});

Given('the TIM.BSCST_FECT_RNG_PARAM parameter table is configured', async function () {
  const isConfigured = await preBillingShellPage.verifyParameterTableConfiguration();
  expect(isConfigured).toBeTruthy();
});

When('I identify the scheduled date and time for GM pre-billing process', async function () {
  await preBillingShellPage.openProcessScheduler();
  await preBillingShellPage.searchGMPreBillingSchedule();
});

Then('I should see the exact start date and time with cutoff on day 29 of the month', async function () {
  const scheduleInfo = await preBillingShellPage.getPreBillingScheduleInfo();
  expect(scheduleInfo.cutoffDay).toBe('29');
  expect(scheduleInfo.startDateTime).toBeTruthy();
});

When('I manually execute the sh_BSCS_ProcesoFacturaGM shell before pre-billing schedule', async function () {
  await preBillingShellPage.navigateToShellExecutionPanel();
  await preBillingShellPage.selectShell('sh_BSCS_ProcesoFacturaGM');
  await preBillingShellPage.executeShellManually();
});

Then('the shell should start correctly and register in the process control table with identifier GM-sequential', async function () {
  const executionStatus = await preBillingShellPage.getShellExecutionStatus();
  expect(executionStatus.started).toBeTruthy();
  const processId = await preBillingShellPage.getProcessControlTableEntry();
  expect(processId).toMatch(/^GM-\d+$/);
});

When('I verify in system logs that the shell does not run simultaneously with IZZIPAY shell', async function () {
  await preBillingShellPage.navigateToSystemLogs();
  await preBillingShellPage.filterLogsByShellExecution();
});

Then('I should see both shells execute at different times without conflicts in shared tables', async function () {
  const conflictCheck = await preBillingShellPage.checkShellExecutionConflicts();
  expect(conflictCheck.hasConflicts).toBeFalsy();
  expect(conflictCheck.gmShellTime).not.toBe(conflictCheck.izzipayShellTime);
});

When('I confirm the shell completes and generates OCCs in Document All table before pre-billing starts', async function () {
  await preBillingShellPage.waitForShellCompletion();
  await preBillingShellPage.navigateToDocumentAllTable();
});

Then('the In Pool Service and In Pool Granel Service OCCs should be registered and available for standard pre-billing', async function () {
  const inPoolOCC = await preBillingShellPage.verifyOCCRegistration('In Pool Service');
  const inPoolGranelOCC = await preBillingShellPage.verifyOCCRegistration('In Pool Granel Service');
  expect(inPoolOCC.registered).toBeTruthy();
  expect(inPoolGranelOCC.registered).toBeTruthy();
  expect(inPoolOCC.availableForPreBilling).toBeTruthy();
  expect(inPoolGranelOCC.availableForPreBilling).toBeTruthy();
});

When('the standard pre-billing process starts after shell completion', async function () {
  await preBillingShellPage.navigateToPreBillingMonitor();
  await preBillingShellPage.waitForPreBillingStart();
});

Then('pre-billing should process the OCCs generated by the shell without errors or inconsistencies', async function () {
  const preBillingStatus = await preBillingShellPage.getPreBillingProcessingStatus();
  expect(preBillingStatus.errors).toHaveLength(0);
  expect(preBillingStatus.inconsistencies).toHaveLength(0);
  expect(preBillingStatus.occsProcessed).toBeGreaterThan(0);
});